name: Deploy

on:
  pull_request:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update stable nightly
          rustup component add --toolchain stable clippy
          rustup component add --toolchain nightly rustfmt
          rustup default stable

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Run fmt
        if: always()
        run: make fmt-check

      - name: Run clippy
        if: always()
        run: make lint

      - name: Run tests
        if: always()
        run: make test

      - name: Build examples
        if: always()
        run: make examples

      - name: Cargo login
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo login $CARGO_REGISTRY_TOKEN

      - name: Publish
        run: |
          cargo publish --dry-run
